/// Copyright 2007 by Inland Imaging Business Associates
/// IIBAENSEMBLE.csp.SupportPageDefinition.Admin
Class IIBAENSEMBLE.csp.SupportPageDefinition.Admin Extends %ZEN.application
{

/// This is the name of this application.
Parameter APPLICATIONNAME = "SupporPageDefinitionAdmin";

/// This is the URL of the main starting page of this application.
Parameter HOMEPAGE = "IIBAENSEMBLE.csp.SupportPageDefinition.Home.cls";

/// This Style block contains application-wide CSS style definitions.
XData Style
{
<style type="text/css">
</style>
}

}
