/// Copyright 2007 by Inland Imaging Business Associates
/// IIBAENSEMBLE.Task.TaskItemDefinitionAdmin.Admin
Class IIBAENSEMBLE.Task.TaskItemDefinitionAdmin.Admin Extends %ZEN.application
{

/// This is the name of this application.
Parameter APPLICATIONNAME = "TaskItemDefinitionAdmin";

/// This is the URL of the main starting page of this application.
Parameter HOMEPAGE = "IIBAENSEMBLE.Task.TaskItemDefinitionAdmin.Home.cls";

/// This Style block contains application-wide CSS style definitions.
XData Style
{
<style type="text/css">
</style>
}

}
