/// Application for the Nuvodia Zen Toolkit.
Class IIBAENSEMBLE.Zen.Toolkit Extends %ZEN.application
{

/// This is the name of this application.
Parameter APPLICATIONNAME = "Nuvodia Zen Toolkit";

/// This is the URL of the main starting page of this application.
Parameter HOMEPAGE;

/// This Style block contains application-wide CSS style definitions.
XData Style
{
<style type="text/css">
</style>
}

}
