Class IIBAENSEMBLE.msg.StreamContainer Extends (Ens.Request, Ens.StreamContainer)
{

Storage Default
{
<Data name="Attributes">
<Attribute>Attributes</Attribute>
<Structure>subnode</Structure>
<Subscript>"IIBAENSEMBLE.msg.StreamContainer.Attributes"</Subscript>
</Data>
<Data name="StreamContainerDefaultData">
<Subscript>"StreamContainer"</Subscript>
<Value name="1">
<Value>OriginalFilename</Value>
</Value>
<Value name="2">
<Value>Type</Value>
</Value>
<Value name="3">
<Value>StreamFC</Value>
</Value>
<Value name="4">
<Value>StreamFB</Value>
</Value>
<Value name="5">
<Value>StreamGC</Value>
</Value>
<Value name="6">
<Value>StreamGB</Value>
</Value>
<Value name="7">
<Value>StreamCF</Value>
</Value>
<Value name="8">
<Value>StreamBF</Value>
</Value>
<Value name="9">
<Value>StreamCG</Value>
</Value>
<Value name="10">
<Value>StreamBG</Value>
</Value>
<Value name="11">
<Value>CharEncodingTable</Value>
</Value>
<Value name="12">
<Value>OutputFolder</Value>
</Value>
<Value name="13">
<Value>OutputFilename</Value>
</Value>
</Data>
<DefaultData>StreamContainerDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
